DeecastZoneCC/Controllers/TestimonialsController.cs
using MyApp.db.MyAppBal;
using MyApp.Entity;
using MyApp.Entity.Message;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeecastZoneCC.Controllers
{
    public class TestimonialsController : Controller
    {
        // GET: Testimonials

        EntitySysUser oSysUser = null;
        String errMsg = String.Empty;
        DataTable dt;  
        public ActionResult Index()
        {

            try
            {
                if (Session["oSysUser"] != null)
                {
                    oSysUser = (EntitySysUser)Session["oSysUser"];
                    oSysUser.USER_KEY = Convert.ToInt32(Session["USER_KEY"]);

                    oSysUser.TAG_PAGE_REFRESH = Server.UrlEncode(System.DateTime.Now.ToString());
                    errMsg = String.Empty;
                  

                    FillTestimonialGrid();
                    ViewBag.hf_MAST_TESTIMONIALS_KEY = "0";



                }
                else
                {

                    return Redirect("~/Admin/Index");
                }
            }
            catch (Exception ex)
            {
                TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgErrCommon + "');");
                // MessageBox(1, Message.msgErrCommon, ex.Message);
            }
            return View(dt.Rows);

        }


        [HttpPost]
        public ActionResult Add()
        {
            try
            {
                // errMsg = String.Empty;
                ViewBag.hf_MAST_TESTIMONIALS_KEY = "0";

                ViewBag.JavaScriptFunction = string.Format("OpenTab2();");
                ViewBag.img_CLIENT = "/Content/admin-assets/images/no_image.jpg";
                dt = FillTestimonialGrid();

                //TempData["JavaScriptFunction"] = string.Format("OpenTab2();");
                //ClearControl();
                //MessageBox(2, "", "");
            }
            catch (Exception ex)
            {
                //  MessageBox(1, Message.msgErrCommon, ex.Message);
                TempData["JavaScriptMsg"] = string.Format("OpenTab2('" + Message.msgErrCommon + "');");
            }

            return View("Index", dt.Rows);
        }


        private DataTable FillTestimonialGrid()
        {
            try
            {
                errMsg = String.Empty;
                System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");
                dt = new DataTable();
                using (BATestimonials oBMC = new BATestimonials())
                {
                    dt = oBMC.GetTestimonial<Int32>("GET", 0, "", ref errMsg, "2019", 1);
              
                    System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-GB");
                }
             
                return dt;
                //return errMsg;
            }
            catch (Exception ex)
            {
                return dt;
            }

        }

        private String ProcessTestimonialImage(ref String Doc_Name, HttpPostedFileBase file)
        {

            if (file == null)
            {
                ViewBag.CLIENT_IMAGE = Request["hf_CLIENT_IMAGE"];
                //ViewBag.LOGO_NAME = Request[ViewBag.hf_LOGO_NAME];
                return String.Empty;
            }
            else
            {
                String[] ImageAcceptedExtensions = null;
                String DOC_PATH = "~" + ConfigurationManager.AppSettings["CLIENT"].ToString();
                try
                {

                    var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp", ".svg" };


                    var Image_url = file.ToString(); //getting complete url
                    var fileName = Path.GetFileName(file.FileName); //getting only file name(ex-ganesh.jpg)  
                    var ext = Path.GetExtension(file.FileName); //getting the extension(ex-.jpg)  
                    if (allowedExtensions.Contains(ext)) //check what type of extension  
                    {
                        string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                        string myfile = System.DateTime.Now.ToString("yyyyMMdd_hhmmss") + "-C" + ext; //appending the name with id  
                                                                                                      // store the file inside ~/project folder(Img)  
                        var path = Server.MapPath(DOC_PATH + myfile);
                        Image_url = path;
                        var imgpath = myfile;
                        file.SaveAs(path);

                        ViewBag.CLIENT_IMAGE = imgpath;

                    }
                    else
                    {
                        ViewBag.message = "Please choose only Image file";
                    }


                    return String.Empty;
                }
                catch (Exception ex)
                {
                    return ex.Message;
                }
                finally
                {
                    ImageAcceptedExtensions = null;
                }
            }
        }

        [HttpPost]
        public ActionResult btn_Testimonial_Save_Click(FormCollection form, HttpPostedFileBase fu_Blog)
        {
            Byte vRef = 0; Int32 vKey = 0;
            String CLIENT_IMAGE = String.Empty;
            EntitySiteSetting oBMAST = null;

            try
            {
                if (ModelState.IsValid)
                {


                    errMsg = ProcessTestimonialImage(ref CLIENT_IMAGE, fu_Blog);
                    if (!String.IsNullOrEmpty(errMsg))
                    {
                        return Redirect("~/SiteSetting/Index");
                    }

                    errMsg = String.Empty;
                    oBMAST = new EntitySiteSetting();
                    oBMAST.MAST_TESTIMONIALS_KEY = Convert.ToInt32(form["hf_MAST_TESTIMONIALS_KEY"] == "" ? "0" : form["hf_MAST_TESTIMONIALS_KEY"]);
                    oBMAST.CLIENT_NAME = form["txt_CLIENT_NAME"];
                    oBMAST.CLIENT_FEEDBACK = form["txt_DESCRIPTION"];
                    oBMAST.CLIENT_IMAGE = ViewBag.CLIENT_IMAGE;
                    DateTime dtBlog_Date = Convert.ToDateTime(form["txt_DATE"].Trim());
                    oBMAST.POSTING_DATE = Convert.ToDateTime(dtBlog_Date);
                    oBMAST.ENT_USER_KEY = Convert.ToInt32(Session["USER_KEY"]);
                    oBMAST.EDIT_USER_KEY = Convert.ToInt32(Session["USER_KEY"]);
                    oBMAST.TAG_ACTIVE = 1;
                    oBMAST.TAG_DELETE = 0;
                    System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-GB");

                    using (BATestimonials oBMC = new BATestimonials())
                    {
                        if (oBMAST.MAST_TESTIMONIALS_KEY == 0)
                        {
                            vRef = oBMC.SaveTestimonial<Object, Int32>("INSERT", oBMAST, null, ref vKey, ref errMsg, "2019", 1);
                            if (vRef == 1)
                            {
                                TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgSaveNew + "');");
                                return Redirect("~/Testimonials/Index");
                            }
                            else if (vRef == 2)
                            {
                                TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgSaveDuplicate + "');");
                             
                                return Redirect("~/Testimonials/Index");
                            }

                            else
                            {
                                TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgSaveErr + "');");
                   
                                return Redirect("~/Testimonials/Index");
                            }

                        }
                        else
                        {
                            vRef = oBMC.SaveTestimonial<Object, Int32>("UPDATE", oBMAST, null, ref vKey, ref errMsg, "2019", 1);
                            if (vRef == 1)
                            {
                               
                                TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgSaveEdit + "');");
                           
                              
                                return Redirect("~/Testimonials/Index");
                            }
                            else if (vRef == 2)
                            {
                                TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgSaveDuplicate + "');");
                                return Redirect("~/Testimonials/Index");
                            
                            }

                            else
                            {
                                TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgSaveErr + "');");
                                return Redirect("~/Testimonials/Index");
              
                            }

                        }


                    }

                }
                else
                {
                    TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgErrCommon + "');");
                  
                }
                return Redirect("~/Testimonials/Index");
            }
            catch (Exception ex)
            {
                TempData["JavaScriptMsg"] = string.Format("OpenTab1('" + Message.msgErrCommon + "');");
              
            }
            finally
            {
                if (oBMAST != null)
                    oBMAST = null;

DeecastZoneCC/Views/Testimonials/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@section FormName{

    <i class="icon-home2 mr-2"></i>Testimonials

}

@section StyleCss{
    <style type="text/css">
        .filename {
            text-overflow: ellipsis;
            overflow: hidden;
            white-space: nowrap;
        }

        .preview {
            height: 230px;
        }
    </style>
}



<script type="text/javascript">

    function OpenTab1(strMsg, error) {
        $("#tab1").fadeIn();
        $("#tab3").hide();
        $("#tab2").hide();

        if ($.trim(strMsg) != '') {
            if (error == 1)
                openErrorPopup(strMsg);
            else
                openSuccessPopup(strMsg);
        }
    }

    function OpenTab2(strMsg, error) {
        $("#tab1").hide();
        $("#tab3").hide();
        $("#tab2").fadeIn();
        if ($.trim(strMsg) != '') {
            if (error == 1)
                openErrorPopup(strMsg);
            else
                openSuccessPopup(strMsg);
        }
    }

    function OpenTab3(strMsg, error) {
        $("#tab1").hide();
        $("#tab3").fadeIn();
        $("#tab2").hide();

        if ($.trim(strMsg) != '') {
            if (error == 1)
                openErrorPopup(strMsg);
            else
                openSuccessPopup(strMsg);
        }
    }

    $(document).ready(function () {
        setDatatable("gvBlogs");
        $('#loadingMask').fadeOut();


        $("#ddl_MAST_BLOG_CATEGORY_KEY").select2({
            placeholder: 'Select Blog Category'
        });

        $('#ddl_MAST_BLOG_CATEGORY_KEY').on('change', function () {
            $('#hf_MAST_BLOG_CATEGORY_KEY').val($(this).val());
        });



        $('.form-input-styled').uniform({
            fileButtonClass: 'action btn bg-pink-400'
        });

        $("#txt_DESCRIPTION").summernote({
            height: 180,
            codemirror: { "theme": "ambiance" }
        });


        $("#txt_DATE").datepicker({

            dateFormat: 'dd/mm/yy',
            showOn: "button",
            buttonImage: "../Content/admin-assets/images/calendar.png",
            buttonImageOnly: true,
            changeMonth: true,
            changeYear: true
        });


        $("#txt_DESCRIPTION").on('summernote.blur', function () {
            $("#txt_DESCRIPTION").html($("#txt_DESCRIPTION").summernote('code'));
        });

        $("#fu_Blog").on("change", function (evt) {
            var tgt = evt.target || window.event.srcElement, files = tgt.files;
            if (files.length > 0) {
                if (files[0].size > 20097134) {
                    $(this).val("");
                    $(this).next(".filename").text("No file selected");
                    $('#img_Blog').attr("src", "~/Content/admin-assets/images/no_image.jpg");
                    $(this).focus();
                    openErrorPopup("Please maintain allowed document size (20MB maximum).");
                }
                else {
                    readURL(this, $('#img_Blog'));
                }
            }
            else {
                $('#img_Blog').attr("src", "~/Content/admin-assets/images/no_image.jpg");
            }
        });



        $("#btn_Head_Save").click(function () {
            if ($("#txt_BLOG_HEADING").val().trim() == "") {
                $("#txt_BLOG_HEADING").focus();
                alert("Blog heading can't left blank");
                return false;
            }


            if ($("#hf_MAST_BLOG_CATEGORY_KEY").val().trim() == "0") {
                $("#LB_MAST_BLOG_CATEGORY_KEY").focus();
                alert("Must Select Blog Category");
                return false;
            }
            if ($("#txt_DATE").val().trim() == "") {
                alert("please select Blog date.");
                $("#txt_DATE").focus();
                return false;
            }
            if ($("#txt_DESCRIPTION").val().trim() == "") {
                alert("please select Description.");
                $("#txt_DESCRIPTION").focus();
                return false;
            }
        });

    });

</script>



<div class="content" style="min-height: 10px;">
    <ul id="fbAdd" class="fab-menu fab-menu-fixed fab-menu-bottom-right">
        <li>
            @using (Html.BeginForm("Add", "Testimonials", FormMethod.Post, new { id = "submitaddform" }))
            {
                <a id="A2" href="#" class="fab-menu-btn btn bg-green btn-float rounded-round btn-icon" onclick="btn_Add_Click();">
                    <i class="fab-icon-open icon-plus3"></i><i class="fab-icon-close icon-cross2"></i>
                </a>
            }
        </li>
    </ul>
    <div id="tab1" class="card">
        <div class="card-body">
            <table cellspacing="0" rules="all" class="table table-hover table-bordered table-striped" border="1" id="gvBlogs" name="gvBlogs" style="border-collapse:collapse;">
                <tbody>
                    <tr>
                        <th>Name</th>
                        <th>Date</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    @foreach (System.Data.DataRow dr in Model)
                    {
                        <tr>

                            <td>@dr["CUST_NAME"].ToString()</td>
                            <td>@dr["POSTING_DATE"].ToString()</td>
                            <td>
                                @using (Html.BeginForm("edit", "Testimonials", FormMethod.Post, new { id = "submitE+" + dr["MAST_TESTIMONIALS_KEY"].ToString() + "" }))
                                {

                                    <input type="hidden" name="editid=" value="@dr["MAST_TESTIMONIALS_KEY"].ToString()" />

                                    <a id="submitE+@dr["MAST_TESTIMONIALS_KEY"].ToString()" href="#" onclick="postmethodusingjs(this.id)" class="list-icons-item"><i class="icon-menu9"></i></a>

                                }
                            </td>
                            <td>
                                @using (Html.BeginForm("delete", "Testimonials", FormMethod.Post, new { id = "submitD+" + dr["MAST_TESTIMONIALS_KEY"].ToString() + "" }))
                                {

                                    <input type="hidden" name="editid=" value="@dr["MAST_TESTIMONIALS_KEY"].ToString()" />

                                    <a id="submitD+@dr["MAST_TESTIMONIALS_KEY"].ToString()" href="#" onclick="postmethodusingjs(this.id)" class="list-icons-item"><i class="icon-trash"></i></a>

                                }
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <ul id="tabsmenu" class="tabsmenu" style="display: none">
        <li class="active"><a id="atab1" href="#tab1">List</a></li>
        <li><a id="atab2" href="#tab2">Add / Edit</a></li>
        <li><a id="aPageName" href="#" style="margin: 0 5px 0 33%; border-radius: 6px;">&nbsp;</a></li>
    </ul>
    <div id="tab2" class="card" style="display:none">

        @using (Html.BeginForm("btn_Testimonial_Save_Click", "Testimonials", FormMethod.Post, new { id = "submitformpage", enctype = "multipart/form-data" }))
        {
            <input type="hidden" id="hf_CLIENT_IMAGE" name="hf_CLIENT_IMAGE" value="@ViewBag.CLIENT_IMAGE" />
            <input type="hidden" id="hf_MAST_TESTIMONIALS_KEY" name="hf_MAST_TESTIMONIALS_KEY" value="@ViewBag.hf_MAST_TESTIMONIALS_KEY" />
           
            <div class="card-body">
                <div class="col-md-12">
                    <fieldset>
                        <legend class="font-weight-semibold">Client Details</legend>
                        <div class="row">
                            <div class="col-md-6">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>
                                            Client Name
                                        </label>
                                        <input type="text" id="txt_CLIENT_NAME" name="txt_CLIENT_NAME" value="@ViewBag.txt_CLIENT_NAME" class="form-control" autofocus />
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>
                                            Date
                                        </label>
                                        <input type="text" id="txt_DATE" name="txt_DATE" value="@ViewBag.txt_DATE" class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <fieldset>
                                    <legend>Client Image</legend>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>
                                                    Upload Client Picture (Accepted Format .png,.svg, .jpg, .jpeg only. Max size 20 MB)
                                                </label>
                                                <input type="file" id="fu_Blog" name="fu_Blog" class="form-input-styled" data-fouc accept=".gif, .svg, .png, .jpg, .jpeg" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-8 ml-auto mr-auto">
                                            <img id="img_Blog" src="@ViewBag.img_CLIENT" class="form-control preview" />
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>
                                        Client Feedback
                                    </label>
                                    <textarea id="txt_DESCRIPTION" name="txt_DESCRIPTION" class="summernote" rows="2">@ViewBag.txt_DESCRIPTION</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <input type="submit" id="btn_Head_Save" value="Submit" class="mb-xs mt-xs btn btn-success" />
                        <input type="button" id="btn_Back_Save" value="Back" class="mb-xs mt-xs mr-xs btn btn-warning" onclick="location.href = '/Blog/Index';" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>


@if (ViewBag.JavaScriptFunction != null)
{

    <script type="text/javascript">
                    @Html.Raw(ViewBag.JavaScriptFunction);
    </script>
}

@if (TempData["JavaScriptMsg"] != null)
{

    <script type="text/javascript">
                    @Html.Raw(TempData["JavaScriptMsg"]);
    </script>
}
<script type="text/javascript">

    function postmethodusingjs(id) {
        /*alert('ok');*/
        document.forms[id].submit();
        return false;
    }

    function postmethodusingheadsavejs() {
        document.forms["submitform"].submit();

        return false;
    }

    function btn_Add_Click() {

        //    alert('ok');
        document.forms["submitaddform"].submit();
        return false;
    }
</script>