DeecastZoneCC/Controllers/BlogUIController.cs
using MyApp.db.Encryption;
using MyApp.db.MyAppBal;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace DeecastZoneCC.Controllers
{
    public class BlogUIController : CommonController
    {
        // GET: BlogUI
        String errMsg = String.Empty, vString = String.Empty;
        DataTable dt = null;
        DataTable dt1 = null;
        DataSet ds = null;
        string[] planname;
        string year;
        string month;
        public ActionResult Index(string id = null, string desc = null, string catid = null)
        {
            Allcatagory();
            bindBlogList();
            layoutpopulate();
            if (id != null)
            {
                if (id == "ARCHIVE")
                {

                    //planname = catid.Split('-');
                    //ViewBag.heading = desc.ToString();
                    month = desc;
                    year = catid;
                    //Checking Query String
                    if (month != null)
                    {
                        if (year != null)
                        {

                            vString = string.Empty;
                            dt = new DataTable();
                            string blogheading;
                            using (BABlog oBME = new BABlog())
                            {
                                dt = oBME.Get("SRH_ARCHIVE", Convert.ToInt32(year), month, ref errMsg, Convert.ToString(DateTime.Now), 1);
                                if (dt != null && dt.Rows.Count > 0)
                                {
                                    for (int i = 0; i < dt.Rows.Count; i++)
                                    {
                                        StringBuilder sb = new StringBuilder(dt.Rows[i]["BLOG_HEADING"].ToString());
                                        sb.Replace(" ", "");
                                        sb.Replace(",", "");
                                        sb.Replace(".", "");
                                        blogheading = Convert.ToString(sb);
                                        vString += "<div class='sec1'><img src='" + ConfigurationManager.AppSettings["BLOG"].ToString() + dt.Rows[i]["BLOG_IMAGE"] + "' alt='" + dt.Rows[0]["BLOG_HEADING"] + "' />"

                       + "<div class='wrap'><h3><a href='" + "/BlogUI/Index/" + Encrypted.EncryptASCII(dt.Rows[i]["MAST_BLOG_KEY"].ToString()) + "/" + blogheading + "'>" + dt.Rows[i]["BLOG_HEADING"] + "</a></h3><h4>Posted on " + dt.Rows[i]["BLOG_DATE"] + "</h4>"
                       + "<p>" + dt.Rows[i]["DESCRIPTION"] + "</p><a href='" + "/BlogUI/Index/" + Encrypted.EncryptASCII(dt.Rows[i]["MAST_BLOG_KEY"].ToString()) + "/" + blogheading + "' class='more-but'>"
                       + "Read More</a></div></div>";
                                    }
                                    ViewBag.blogRender = vString;

                                }
                                else
                                {
                                    ViewBag.blogRender = "<div class='und-blle'><h2>No Blog in this category</p></div>";
                                }
                            }

                        }


                    }
                }
                else
                {
                    if (catid != null)
                    {


                        planname = catid.Split('-');
                        ViewBag.heading = desc.ToString();
                        //Checking Query String
                        if (planname != null)
                        {
                            if (planname != null)
                            {
                                string plan = Convert.ToString(planname[0]);
                                Int32 postKey = Convert.ToInt32(Encrypted.DecryptASCII(plan));
                                vString = string.Empty;
                                dt = new DataTable();
                                string blogheading;
                                using (BABlog oBME = new BABlog())
                                {
                                    dt = oBME.Get("GET_CAT_DTLS", postKey, "", ref errMsg, Convert.ToString(DateTime.Now), 1);
                                    if (dt != null && dt.Rows.Count > 0)
                                    {
                                        for (int i = 0; i < dt.Rows.Count; i++)
                                        {
                                            StringBuilder sb = new StringBuilder(dt.Rows[i]["BLOG_HEADING"].ToString());
                                            sb.Replace(" ", "");
                                            sb.Replace(",", "");
                                            sb.Replace(".", "");
                                            blogheading = Convert.ToString(sb);
                                            vString += "<div class='sec1'><img src='" + ConfigurationManager.AppSettings["BLOG"].ToString() + dt.Rows[i]["BLOG_IMAGE"] + "' alt='" + dt.Rows[0]["BLOG_HEADING"] + "' />"

                        + "<div class='wrap'><h3><a href='" + "/BlogUI/Index/" + Encrypted.EncryptASCII(dt.Rows[i]["MAST_BLOG_KEY"].ToString()) + "/" + blogheading + "'>" + dt.Rows[i]["BLOG_HEADING"] + "</a></h3><h4>Posted on " + dt.Rows[i]["BLOG_DATE"] + "</h4>"
                        + "<p>" + dt.Rows[i]["DESCRIPTION"] + "</p><a href='" + "/BlogUI/Index/" + Encrypted.EncryptASCII(dt.Rows[i]["MAST_BLOG_KEY"].ToString()) + "/" + blogheading + "' class='more-but'>"
                        + "Read More</a></div></div>";
                                        }
                                        ViewBag.blogRender = vString;

                                    }
                                    else
                                    {
                                        ViewBag.blogRender = "<div class='und-blle'><h2>No Blog in this category</p></div>";
                                    }
                                }

                            }


                        }

                    }
                    else if (id != null)
                    {


                        planname = id.Split('-');
                        ViewBag.heading = desc.ToString();
                        //Checking Query String
                        if (planname != null)
                        {
                            if (planname != null)
                            {

                                vString = string.Empty;
                                string plan = Convert.ToString(planname[0]);
                                Int32 postKey = Convert.ToInt32(Encrypted.DecryptASCII(plan));
                                dt = new DataTable();
                                using (BABlog oBME = new BABlog())
                                {
                                    dt = oBME.Get("SRH_KEY", postKey, "", ref errMsg, Convert.ToString(DateTime.Now), 1);
                                    if (dt != null && dt.Rows.Count > 0)
                                    {
                                        ViewBag.title = dt.Rows[0]["BLOG_HEADING"].ToString();
                                        ViewBag.MetaDescription = dt.Rows[0]["META_DESC"].ToString();
                                        ViewBag.MetaKeywords = dt.Rows[0]["META_KEYWORD"].ToString();
                                    }
                                }
                            }


                        }

                        else
                        {
                            dt = new DataTable();
                            using (BABlog oBME = new BABlog())
                            {
                                dt = oBME.Get("ALL_BLOG", 0, "", ref errMsg, Convert.ToString(DateTime.Now), 1);
                            }
                        }

                        if (planname != null)
                        {
                            if (planname != null)
                            {
                                if (dt != null && dt.Rows.Count > 0)
                                {

                                    vString = string.Empty;
                                    string blogheading;
                                    StringBuilder sb = new StringBuilder(dt.Rows[0]["BLOG_HEADING"].ToString());
                                    sb.Replace(" ", "");
                                    sb.Replace(",", "");
                                    sb.Replace(".", "");
                                    blogheading = Convert.ToString(sb);


                                    vString += "<div class='sec1'><img src='" + ConfigurationManager.AppSettings["BLOG"].ToString() + dt.Rows[0]["BLOG_IMAGE"] + "' alt='" + dt.Rows[0]["BLOG_HEADING"] + "' />"

                        + "<div class='wrap'><h3><a href='" + "/BlogUI/Index/" + Encrypted.EncryptASCII(dt.Rows[0]["MAST_BLOG_KEY"].ToString()) + "/" + blogheading + "'>" + dt.Rows[0]["BLOG_HEADING"] + "</a></h3><h4>Posted on " + dt.Rows[0]["BLOG_DATE"] + "</h4>"
                        + "<p>" + dt.Rows[0]["DESCRIPTION"] + "</p><a href='/BlogUI/Index' class='more-but'>"
                        + "Back</a></div></div>";

                                    ViewBag.blogRender = vString;
                                    TempData["jsf"] = String.Format("callingfromjs();");


                                }
                            }

                        }
                        else
                        {
                            //bindBlogList(dt);
                        }
                    }
                }
            }

            return View();
        }

        private void bindBlogList()
        {
            dt = new DataTable();

            string blogheading;

DeecastZoneCC/Views/BlogUI/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section title{
    Blog
}

<section class="inner-banner-part">
    <img class="img1" src="~/Content/main-assets/images/inner-ban.png" alt="">
    <img class="img2" src="~/Content/main-assets/images/banner-shape.png" alt="">
    <div class="ban-tx">
        <h2>Blog</h2>
        <ul>
            <li><a href="#">Home</a>/</li>
            <li>Blog</li>
        </ul>
    </div>
</section>

<section class="Blog-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 decp">
                <h2>Latest News</h2>

                @Html.Raw(ViewBag.blogRender)

                @*<div class="sec1">
                    <img src="~/Content/main-assets/images/blog-img1.png" alt="">
                    <div class="wrap">
                        <h3><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod </a></h3>
                        <h4>__ Jessica Moore, Customer.  |   Posted on 09/01/2020</h4>
                        <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in </p>
                        <a href="#" class="more-but">Read more</a>
                    </div>
                </div>
                <div class="sec1">
                    <img src="~/Content/main-assets/images/blog-img1.png" alt="">
                    <h6>Latest News</h6>
                    <div class="wrap">
                        <h3><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod </a></h3>
                        <h4>__ Jessica Moore, Customer.  |   Posted on 09/01/2020</h4>
                        <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in </p>
                        <a href="#" class="more-but">Read more</a>
                    </div>
                </div>*@
            </div>
            <div class="col-lg-4 side-bar">
                @using (Html.BeginForm("btn_Search_click", "BlogUI", FormMethod.Post, new { id = "submitform", enctype = "multipart/form-data" }))
                {
                    <input type="text" name="txt_Search" id="txt_Search" placeholder="Blog Search....">
                    <button type="submit"><img src="~/Content/main-assets/images/search.svg" alt="Submit" width="40" height="40"></button>
                }
                    <div class="sec1">
                        <h5>Follow us on</h5>
                        <ul class="social">
                            <li><a href="@ViewBag.INSTAGRAM_LINK"><i class="fab fa-instagram"></i></a></li>
                            <li><a href="@ViewBag.LARGE_VIDEO_LINK"><i class="fab fa-youtube"></i></a></li>
                            <li><a href="@ViewBag.FACEBOOK_LINK"><i class="fab fa-facebook-f"></i></a></li>
                        </ul>
                    </div>
                    <div class="sec1">
                        <h5>Categories</h5>
                        <ul class="Categories">
                            @Html.Raw(ViewBag.categoryul)
                            @*<li><a href="#"> Latest News</a></li>
                    <li><a href="#">Special Offers</a></li>
                    <li><a href="#">New Arrivals</a></li>
                    <li><a href="#">Reviews</a></li>*@
                        </ul>
                    </div>
                    <div class="sec1">
                        <h5>Latest Posts</h5>
                        <ul class="Posts">

                            @Html.Raw(ViewBag.ulRecentPosts)

                            @*<li>
                        <a href="#">
                            <img src='~/Content/main-assets/images/blog-img3.png' alt=''>
                            <h4> Lorem ipsum dolor sit amet</h4>
                            <h5>— January 4, 2921</h5>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod </p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="~/Content/main-assets/images/blog-img3.png" alt="">
                            <h4> Lorem ipsum dolor sit amet</h4>
                            <h5>— January 4, 2921</h5>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod </p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="~/Content/main-assets/images/blog-img3.png" alt="">
                            <h4> Lorem ipsum dolor sit amet</h4>
                            <h5>— January 4, 2921</h5>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod </p>
                        </a>
                    </li>*@
                        </ul>
                    </div>
                </div>
        </div>
    </div>
</section>